### ISSUE TITLE
How the "vgg_conv.pth" is generated?

### ISSUE THREAD

**Issue by panovr** [leongatys/PytorchNeuralStyleTransfer#1]
I found that "vgg_conv.pth" only has the conv layers of the original vgg net, and the fc layers are removed. May I ask that how this model is generated?

**Comment by leongatys** [comment]
- Load the full model e.g. from the caffe model zoo 
- Define the network architecture in pytorch that only includes the convolutional part. 
- Copy the numpy arrays of the parameters for the convolutional layers from the full caffe model into the pytorch model. 
- Save the state dict of the pytorch model.

Hope that helps,
Leon

**Comment by panovr** [comment]
Got it, thanks!

**Comment by michaelhuang74** [comment]
@leongatys Thanks for the steps. Could you kindly share the code that converts the caffe model to pytorch model?
