### ISSUE TITLE
Link for downloading vgg unavailable

### ISSUE THREAD

**Issue by LucasAlegre** [leongatys/PytorchNeuralStyleTransfer#10]
Hi,

The link https://bethgelab.org/media/uploads/pytorch_models/vgg_conv.pth from the shell script is currently unavailable. Is there any other way to download it?

Thank you in advance!

**Comment by jrtechs** [comment]
I am getting the same error. I found another project that trained the same model:

https://github.com/paniabhisek/VGG

**but, it is in TensorFlow and this is in PyTorch.

**Comment by leongatys** [comment]
Thanks for letting me know - should be fixed now!

**Comment by jrtechs** [comment]
It works! However, just an FYI, the cert for the website is expired.
