### ISSUE TITLE
vgg model no longer available

### ISSUE THREAD

**Issue by fdan** [leongatys/PytorchNeuralStyleTransfer#17]
This model is no longer available:

http://bethgelab.org/media/uploads/pytorch_models/vgg_conv.pth

I have a local copy if it's useful to re-host somewhere.

**Comment by messierandromeda** [comment]
Where can I find it?

**Comment by fdan** [comment]
I have uploaded and archived copy here:

https://huggingface.co/fdan/neural_style_transfer_vgg/resolve/main/vgg_conv.pth

**Comment by fdan** [comment]
Hi, I have uploaded an archived copy here:

https://huggingface.co/fdan/neural_style_transfer_vgg/resolve/main/vgg_conv.pth
